version: "3"
services:
  node:
    build: "./frontend"
    container_name: "frontend"
    volumes:
      - ./:/usr/src/app
    ports:
      - "3000:3000"
    command: sh -c "cd frontend && yarn start"
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
  go:
    build: "./server"
    container_name: "server"
    tty: true
    volumes:
      - ./:/go/src/work # マウントディレクトリ指定
    ports:
      - "8080:8080"
    command: sh -c "cd server && go run main.go"
    stdin_open: true
  redis:
    image: "redis:latest"
    container_name: "redis"
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/data"