version: "3"
services:
  node:
    build: "./frontend"
    container_name: "frontend"
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "3000:3000"
    command: sh -c "yarn start"
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
  go:
    build: "./api"
    container_name: "api"
    # build: "./server"
    # container_name: "server"
    tty: true
    volumes:
      - ./api:/go/src/work
    ports:
      - "8080:8080"
    command: sh -c "go run main.go"
    stdin_open: true
  redis:
    image: "redis:latest"
    container_name: "redis"
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/data"
  db:
    image: mysql:5.7
    container_name: mysql_host
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: main
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: sh -c "chmod 644 /etc/mysql/conf.d/my.cnf && mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
    volumes:
      - ./data/mysql/data:/var/lib/mysql
      - ./data/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./data/mysql/sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"